### ISSUE TITLE
Write release scripts to prevent more deployment confusion

### ISSUE THREAD

**Issue by JacekLach** [lshift/cloverage#6]
The following steps should be taken for a release:

1. Check that the current branch is in sync with lshift/cloverage:master
2. Run all the tests.
3. Drop -SNAPSHOT suffixes from current version of both projects.
4. Update cloverage version in lein-cloverage/src/leiningen/cloverage.clj
5. `git commit -m 'Release cloverage $VERSION' and lein-cloverage $PLUGIN-VERSION`
6. `git tag -s cloverage-$VERSION`
7. `git tag -s lein-cloverage-$PLUGIN-VERSION`
8. (cd cloverage && lein deploy clojars)
9. (cd lein-cloverage && lein deploy clojars)
10. Bump library and plugin versions for development, add -SNAPSHOT suffixes
11. Commit the version bump.

These two commits should probably happen straight on master.
Another possibly useful script is a 'pull-request-for-issue' script that automatically makes a pull request from your repo/branch to lshift/master for a given issue number.

**Comment by palfrey** [comment]
I've plugged in lein-release and used it to do the new release, so closing this one. It's very simple to use, and now documented in the README
