### ISSUE TITLE
Submit files to Coveralls

### ISSUE THREAD

**Issue by palfrey** [lshift/cloverage#63]
Make it possible to submit the generate Coveralls report without having to do something like the Bash workaround from http://blog.bfontaine.net/2014/02/15/using-coveralls-with-clojure/

**Comment by lvh** [comment]
I think this is resolved in 1.0.7-SNAPSHOT. See it working here:

https://github.com/RackSec/desdemona/blob/master/.travis.yml#L63-L64

**Comment by lvh** [comment]
Closing, since this will be fixed in the next release.
