### ISSUE TITLE
Add midje support

### ISSUE THREAD

**Issue by palfrey** [lshift/cloverage#64]
(Related to #22 and #56, but more explicit)

Reason why the 'Ran x tests containing y assertions.' message doesn't work by default is that Cloverage uses clojure.test/run-tests internally and needs it's results in order to be able to do the right thing. As midje doesn't return the right results for "lein test", it also fails here.

Worse, midje.repl/load-facts doesn't actually return test results. The only way we'd be able to get proper midje support is doing something like https://github.com/glittershark/midje-notifier/blob/master/src/midje/notifier.clj and using the data from the notifier to give us the test result data.

**Comment by joelittlejohn** [comment]
Since coverage is already accurately recorded when using midje, and the only problem seems to the message that states `Ran 0 tests containing 0 assertions.`, can we just remove this message?

**Comment by palfrey** [comment]
@joelittlejohn: No, because we can't easily (AFAIK) tell the difference between someone with only Midje tests, and someone with no tests, and that result is the same either way. Also, removing it is tricky because that's clojure.test doing the output, not Cloverage.

**Comment by rm-hull** [comment]
@lvh -- this issue can be closed

[Midje support was implemented in #125 from @rfkm's branch]

**Comment by lvh** [comment]
Good catch :)
