### ISSUE TITLE
Issue instrumenting Clout CompiledRoute records

### ISSUE THREAD

**Issue by BinarySplit** [lshift/cloverage#66]
I've put a reduced test case here: https://github.com/BinarySplit/cloverage-compojure-repro.git

When running cloverage on this project, I get this exception:

> Testing cloverage-compojure-repro.core-test
> java.lang.ClassCastException: clojure.lang.Cons cannot be cast to java.util.regex.Pattern
> 	at clojure.core$re_matcher.invoke(core.clj:4460)
> 	at clout.core.CompiledRoute.route_matches(core.clj:50)
> 	at compojure.core$if_route$fn__4854.invoke(core.clj:40)
> 	at compojure.core$if_method$fn__4846.invoke(core.clj:27)
> 	at compojure.core$routing$fn__4885.invoke(core.clj:127)
> 	at clojure.core$some.invoke(core.clj:2515)
> 	at compojure.core$routing.doInvoke(core.clj:127)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:139)
> 	at clojure.core$apply.invoke(core.clj:626)
> 	at compojure.core$routes$fn__4889.invoke(core.clj:132)
> ...

This exception wasn't occurring on Cloverage prior to the 935b65f19ec1c66d87377f2fcea73022aa1dc7fd commit, however I have been using [cloverage-compojure-fix](https://github.com/MichaelBlume/cloverage-compojure-fix) to get Cloverage to work correctly on Compojure projects.

This exception started to hit us overnight, and I lost a lot of time figuring out that it was because Lein-Cloverage automatically updates to the latest version of Cloverage whenever there's a new release. My workaround for now is to explicitly set the version of cloverage via command line: `CLOVERAGE_VERSION=1.0.4 lein cloverage` 

I don't know where to go from here to diagnose the underlying cause for this issue. Any ideas?

**Comment by palfrey** [comment]
Thanks for the testcase. Investigating now...

**Comment by MichaelBlume** [comment]
Ah, I have a problem too, it's suggestive that we're both using compojure-api...

**Comment by MichaelBlume** [comment]
Ok, so when I instrument https://github.com/weavejester/clout/blob/master/src/clout/core.clj#L46 to print out the value of ```re```, its value appears to be ```(cloverage.instrument/wrapm cloverage.coverage/track-coverage 125 #"/api/api-docs")``` -- so I think maybe there's some kind of quoting problem? Like it looks like a piece of code is being passed where the data it should evaluate to should be.

**Comment by stuarthalloway** [comment]
;; test case
    (deftest do-wrap-for-record-returns-record
      (is (= (Record. 1) (eval (wrap #'nop 0 (Record. 1))))))

**Comment by palfrey** [comment]
I've got a partial fix as #69, which works by disabling some of the further record wrapping that 935b65f / #59 introduced. It certainly fixes the reduced test case, but if anyone has any larger code bases they want to check against, that would be most welcomed.

Test steps:
1. Checkout #69.
2. Go into cloverage folder, and run `lein install` to install a local snapshot copy of Cloverage.
3. Run `CLOVERAGE_VERSION=1.0.6-SNAPSHOT lein cloverage` against your larger code base

**Comment by palfrey** [comment]
Ha! #69 now has a much better fix, which doesn't disable the existing Record wrapping, but improves it, *and* works with the reduced test case :) Checking with other code bases (using the previously listed steps) is encouraged before I merge it however.

**Comment by palfrey** [comment]
Merging of #69 appears to now fix this. New release sometime soon...
